repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint (black + ruff + mypy)
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true

      - id: test
        name: Run tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
