[project]
name = "reqtools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.6.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "fastapi>=0.118.0",
    "uvicorn>=0.37.0",
]
